[package]
name = "superdiff"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.1"
clap = { version = "4.0.15", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lev_early_escape"
harness = false
